# サイトの基本設定
title: ゆっくりええAんばいI
description: |
  田舎でちょっとだけお米を作ってのんびり暮らしております。
  プログラムどころか、文字入力さえままならない。
  そんなおじいちゃんがAIと会話をしていたら、こんなサイトができてしまいました。
  このサイトは「ゆっくりええAんばいI」をモットーにのんびり作っていきます。
  見てくれて、本当にありがとう。

theme: minima

future: true
