# サイトの基本設定
title: ゆっくりええAんばいI
description: |
  田舎で、ちょっとだけお米を作ってのんびり暮らしております。
  プログラムどころか、文字入力さえままならない。
  そんなおじいちゃんがAIと会話をしていたら、なんだか、こんなサイトができてしまいました。
  このサイトは「ゆっくりええAんばいI」をモットーにのんびり作っていきます。
  見てくれて、本当にありがとう。

# GitHub Pagesのテーマ設定
theme: null
